export const GET_SOURCING = "GET_SOURCING";
export const GET_SOURCING_SUCCESS = "GET_SOURCING_SUCCESS";
export const GET_SOURCING_FAIL = "GET_SOURCING_FAIL";

export const GET_SPECIFIC_SOURCING = "GET_SPECIFIC_SOURCING";
export const GET_SPECIFIC_SOURCING_SUCCESS = "GET_SPECIFIC_SOURCING_SUCCESS";
export const GET_SPECIFIC_SOURCING_FAIL = "GET_SPECIFIC_SOURCING_FAIL";

export const POST_SOURCING = "POST_SOURCING";
export const POST_SOURCING_SUCCESS = "POST_SOURCING_SUCCESS";
export const POST_SOURCING_FAIL = "POST_SOURCING_FAIL";

export const UPDATE_SOURCING = "UPDATE_SOURCING";
export const UPDATE_SOURCING_SUCCESS = "UPDATE_SOURCING_SUCCESS";
export const UPDATE_SOURCING_FAIL = "UPDATE_SOURCING_FAIL";

export const RESET_SOURCING_STATUS = "RESET_SOURCING_STATUS";

export const DELETE_SOURCING = "DELETE_SOURCING";
export const DELETE_SOURCING_SUCCESS = "DELETE_SOURCING_SUCCESS";
export const DELETE_SOURCING_FAIL = "DELETE_SOURCING_FAIL";
