export const GET_SALES_UNIT = "GET_SALES_UNIT";
export const GET_SALES_UNIT_SUCCESS = "GET_SALES_UNIT_SUCCESS";
export const GET_SALES_UNIT_FAIL = "GET_SALES_UNIT_FAIL";

export const UPDATE_SALES_UNIT = "UPDATE_SALES_UNIT";
export const UPDATE_SALES_UNIT_SUCCESS = "UPDATE_SALES_UNIT_SUCCESS";
export const UPDATE_SALES_UNIT_FAIL = "UPDATE_SALES_UNIT_FAIL";

export const ADD_SALES_UNIT = "ADD_SALES_UNIT";
export const ADD_SALES_UNIT_SUCCESS = "ADD_SALES_UNIT_SUCCESS";
export const ADD_SALES_UNIT_FAIL = "ADD_SALES_UNIT_FAIL";

export const DELETE_SALES_UNIT = "DELETE_SALES_UNIT";
export const DELETE_SALES_UNIT_SUCCESS = "DELETE_SALES_UNIT_SUCCESS";
export const DELETE_SALES_UNIT_FAIL = "DELETE_SALES_UNIT_FAIL";
