export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_FAIL = "GET_USERS_FAIL";

export const ADD_NEW_USER = "ADD_NEW_USER";
export const ADD_NEW_USER_SUCCESS = "ADD_NEW_USER_SUCCESS";
export const ADD_NEW_USER_FAIL = "ADD_NEW_USER_FAIL";

export const UPDATE_NEW_USER = "UPDATE_NEW_USER";
export const UPDATE_NEW_USER_SUCCESS = "UPDATE_NEW_USER_SUCCESS";
export const UPDATE_NEW_USER_FAIL = "UPDATE_NEW_USER_FAIL";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const GET_QUANTITY = "GET_QUANTITY";
export const GET_QUANTITY_SUCCESS = "GET_QUANTITY_SUCCESS";
export const GET_QUANTITY_FAIL = "GET_QUANTITY_FAIL";

export const QUANTITY_CHANGE = "QUANTITY_CHANGE";

export const UPDATE_REMAINING_QUANTITY = "UPDATE_REMAINING_QUANTITY";
export const UPDATE_REMAINING_QUANTITY_SUCCESS =
  "UPDATE_REMAINING_QUANTITY_SUCCESS";
export const UPDATE_REMAINING_QUANTITY_FAIL = "UPDATE_REMAINING_QUANTITY_FAIL";

export const RESET_ERROR = "RESET_ERROR";

export const GET_SPECIFIC_USER = "GET_SPECIFIC_USER";
export const GET_SPECIFIC_USER_SUCCESS = "GET_SPECIFIC_USER_SUCCESS";
export const GET_SPECIFIC_USER_FAIL = "GET_SPECIFIC_USER_FAIL";

export const UPDATE_SHIPPING_INFO = "UPDATE_SHIPPING_INFO";
export const UPDATE_SHIPPING_INFO_SUCCESS = "UPDATE_SHIPPING_INFO_SUCCESS";
export const UPDATE_SHIPPING_INFO_FAIL = "UPDATE_SHIPPING_INFO_FAIL";

export const ADD_NEW_SHIPPING_INFO = "ADD_NEW_SHIPPING_INFO";
export const ADD_NEW_SHIPPING_INFO_SUCCESS = "ADD_NEW_SHIPPING_INFO_SUCCESS";
export const ADD_NEW_SHIPPING_INFO_FAIL = "ADD_NEW_SHIPPING_INFO_FAIL";

export const DELETE_SHIPPING_INFO = "DELETE_SHIPPING_INFO";
export const DELETE_SHIPPING_INFO_SUCCESS = "DELETE_SHIPPING_INFO_SUCCESS";
export const DELETE_SHIPPING_INFO_FAIL = "DELETE_SHIPPING_INFO_FAIL";

export const GET_SHIPPING_INFO = "GET_SHIPPING_INFO";
export const GET_SHIPPING_INFO_SUCCESS = "GET_SHIPPING_INFO_SUCCESS";
export const GET_SHIPPING_INFO_FAIL = "GET_SHIPPING_INFO_FAIL";

export const CLEAR_SHIPPING_INFO = "CLEAR_SHIPPING_INFO";

export const GET_ALL_SHIPPING_INFO = "GET_ALL_SHIPPING_INFO";
export const GET_ALL_SHIPPING_INFO_SUCCESS = "GET_ALL_SHIPPING_INFO_SUCCESS";
export const GET_ALL_SHIPPING_INFO_FAIL = "GET_ALL_SHIPPING_INFO_FAIL";

export const GET_VENDOR = "GET_VENDOR";
export const GET_VENDOR_SUCCESS = "GET_VENDOR_SUCCESS";
export const GET_VENDOR_FAIL = "GET_VENDOR_FAIL";

export const ADD_VENDOR = "ADD_VENDOR";
export const ADD_VENDOR_SUCCESS = "ADD_VENDOR_SUCCESS";
export const ADD_VENDOR_FAIL = "ADD_VENDOR_FAIL";

export const UPDATE_VENDOR = "UPDATE_VENDOR";
export const UPDATE_VENDOR_SUCCESS = "UPDATE_VENDOR_SUCCESS";
export const UPDATE_VENDOR_FAIL = "UPDATE_VENDOR_FAIL";

export const DELETE_VENDOR = "DELETE_VENDOR";
export const DELETE_VENDOR_SUCCESS = "DELETE_VENDOR_SUCCESS";
export const DELETE_VENDOR_FAIL = "DELETE_VENDOR_FAIL";

export const GET_ALL_VENDOR = "GET_ALL_VENDOR";
export const GET_ALL_VENDOR_SUCCESS = "GET_ALL_VENDOR_SUCCESS";
export const GET_ALL_VENDOR_FAIL = "GET_ALL_VENDOR_FAIL";

export const ADD_BANKING_INFO = "ADD_BANKING_INFO";
export const ADD_BANKING_INFO_SUCCESS = "ADD_BANKING_INFO_SUCCESS";
export const ADD_BANKING_INFO_FAIL = "ADD_BANKING_INFO_FAIL";

export const DELETE_BANKING_INFO = "DELETE_BANKING_INFO";
export const DELETE_BANKING_INFO_SUCCESS = "DELETE_BANKING_INFO_SUCCESS";
export const DELETE_BANKING_INFO_FAIL = "DELETE_BANKING_INFO_FAIL";

export const GET_BANKING_INFO = "GET_BANKING_INFO";
export const GET_BANKING_INFO_SUCCESS = "GET_BANKING_INFO_SUCCESS";
export const GET_BANKING_INFO_FAIL = "GET_BANKING_INFO_FAIL";

export const UPDATE_BANKING_INFO = "UPDATE_BANKING_INFO";
export const UPDATE_BANKING_INFO_SUCCESS = "UPDATE_BANKING_INFO_SUCCESS";
export const UPDATE_BANKING_INFO_FAIL = "UPDATE_BANKING_INFO_FAIL";

export const RESET_USER = "RESET_USER";
