export const GET_INVOICE = "GET_INVOICE";
export const GET_INVOICE_SUCCESS = "GET_INVOICE_SUCCESS";
export const GET_INVOICE_FAIL = "GET_INVOICE_FAIL";

export const GET_SPECIFIC_INVOICE = "GET_SPECIFIC_INVOICE";
export const GET_SPECIFIC_INVOICE_SUCCESS = "GET_SPECIFIC_INVOICE_SUCCESS";
export const GET_SPECIFIC_INVOICE_FAIL = "GET_SPECIFIC_INVOICE_FAIL";

export const POST_INVOICE = "POST_INVOICE";
export const POST_INVOICE_SUCCESS = "POST_INVOICE_SUCCESS";
export const POST_INVOICE_FAIL = "POST_INVOICE_FAIL";

export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const UPDATE_INVOICE_SUCCESS = "UPDATE_INVOICE_SUCCESS";
export const UPDATE_INVOICE_FAIL = "UPDATE_INVOICE_FAIL";

export const RESET_INVOICE_STATUS = "RESET_INVOICE_STATUS";

export const DELETE_INVOICE = "DELETE_INVOICE";
export const DELETE_INVOICE_SUCCESS = "DELETE_INVOICE_SUCCESS";
export const DELETE_INVOICE_FAIL = "DELETE_INVOICE_FAIL";
