export default {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  ROLE: "ROLE",
  AUTH_USER: "authUser",
  ADMIN_ROLE_ID: 1000,
  USER_ROLE_ID: 1001,
  COMPANY_NAME: "COMPANY_NAME",
  DEFAULT_ADMIN_MAIN_ROUTE: "/admin-panel",
  DEFAULT_USER_MAIN_ROUTE: "/quotation"
};

