export const GET_QUOTATION = "GET_QUOTATION";
export const GET_QUOTATION_SUCCESS = "GET_QUOTATION_SUCCESS";
export const GET_QUOTATION_FAIL = "GET_QUOTATION_FAIL";

export const GET_SPECIFIC_QUOTATION = "GET_SPECIFIC_QUOTATION";
export const GET_SPECIFIC_QUOTATION_SUCCESS = "GET_SPECIFIC_QUOTATION_SUCCESS";
export const GET_SPECIFIC_QUOTATION_FAIL = "GET_SPECIFIC_QUOTATION_FAIL";

export const POST_QUOTATION = "POST_QUOTATION";
export const POST_QUOTATION_SUCCESS = "POST_QUOTATION_SUCCESS";
export const POST_QUOTATION_FAIL = "POST_QUOTATION_FAIL";

export const UPDATE_QUOTATION = "UPDATE_QUOTATION";
export const UPDATE_QUOTATION_SUCCESS = "UPDATE_QUOTATION_SUCCESS";
export const UPDATE_QUOTATION_FAIL = "UPDATE_QUOTATION_FAIL";

export const RESET_QUOTATION_STATUS = "RESET_QUOTATION_STATUS";

export const DELETE_QUOTATION = "DELETE_QUOTATION";
export const DELETE_QUOTATION_SUCCESS = "DELETE_QUOTATION_SUCCESS";
export const DELETE_QUOTATION_FAIL = "DELETE_QUOTATION_FAIL";

export const GET_REASONING_LIST = "GET_REASONING_LIST";
export const GET_REASONING_LIST_SUCCESS = "GET_REASONING_LIST_SUCCESS";
export const GET_REASONING_LIST_FAIL = "GET_REASONING_LIST_FAIL";

export const SUBMIT_REASON = "SUBMIT_REASON";
export const SUBMIT_REASON_SUCCESS = "SUBMIT_REASON_SUCCESS";
export const SUBMIT_REASON_FAIL = "SUBMIT_REASON_FAIL";
