export const GET_SITES = "GET_SITES";
export const GET_SITES_SUCCESS = "GET_SITES_SUCCESS";
export const GET_SITES_FAIL = "GET_SITES_FAIL";

export const GET_SPECIFIC_SITES = "GET_SPECIFIC_SITES";
export const GET_SPECIFIC_SITES_SUCCESS = "GET_SPECIFIC_SITES_SUCCESS";
export const GET_SPECIFIC_SITES_FAIL = "GET_SPECIFIC_SITES_FAIL";

export const UPDATE_SITES = "UPDATE_SITES";
export const UPDATE_SITES_SUCCESS = "UPDATE_SITES_SUCCESS";
export const UPDATE_SITES_FAIL = "UPDATE_SITES_FAIL";

export const ADD_SITES = "ADD_SITES";
export const ADD_SITES_SUCCESS = "ADD_SITES_SUCCESS";
export const ADD_SITES_FAIL = "ADD_SITES_FAIL";

export const DELETE_SITES = "DELETE_SITES";
export const DELETE_SITES_SUCCESS = "DELETE_SITES_SUCCESS";
export const DELETE_SITES_FAIL = "DELETE_SITES_FAIL";
