export const GET_PURCHASE_ORDER = "GET_PURCHASE_ORDER";
export const GET_PURCHASE_ORDER_SUCCESS = "GET_PURCHASE_ORDER_SUCCESS";
export const GET_PURCHASE_ORDER_FAIL = "GET_PURCHASE_ORDER_FAIL";

export const GET_SPECIFIC_PURCHASE_ORDER = "GET_SPECIFIC_PURCHASE_ORDER";
export const GET_SPECIFIC_PURCHASE_ORDER_SUCCESS =
  "GET_SPECIFIC_PURCHASE_ORDER_SUCCESS";
export const GET_SPECIFIC_PURCHASE_ORDER_FAIL =
  "GET_SPECIFIC_PURCHASE_ORDER_FAIL";

export const POST_PURCHASE_ORDER = "POST_PURCHASE_ORDER";
export const POST_PURCHASE_ORDER_SUCCESS = "POST_PURCHASE_ORDER_SUCCESS";
export const POST_PURCHASE_ORDER_FAIL = "POST_PURCHASE_ORDER_FAIL";

export const UPDATE_PURCHASE_ORDER = "UPDATE_PURCHASE_ORDER";
export const UPDATE_PURCHASE_ORDER_SUCCESS = "UPDATE_PURCHASE_ORDER_SUCCESS";
export const UPDATE_PURCHASE_ORDER_FAIL = "UPDATE_PURCHASE_ORDER_FAIL";

export const RESET_PURCHASE_ORDER_STATUS = "RESET_PURCHASE_ORDER_STATUS";

export const DELETE_PURCHASE_ORDER = "DELETE_PURCHASE_ORDER";
export const DELETE_PURCHASE_ORDER_SUCCESS = "DELETE_PURCHASE_ORDER_SUCCESS";
export const DELETE_PURCHASE_ORDER_FAIL = "DELETE_PURCHASE_ORDER_FAIL";

export const UPDATE_PURCHASE_ORDER_REASON = "UPDATE_PURCHASE_ORDER_REASON";
export const UPDATE_PURCHASE_ORDER_REASON_SUCCESS =
  "UPDATE_PURCHASE_ORDER_REASON_SUCCESS";
export const UPDATE_PURCHASE_ORDER_REASON_FAIL =
  "UPDATE_PURCHASE_ORDER_REASON_FAIL";
