export const GET_CURRENCY_CODE = "GET_CURRENCY_CODE";
export const GET_CURRENCY_CODE_SUCCESS = "GET_CURRENCY_CODE_SUCCESS";
export const GET_CURRENCY_CODE_FAIL = "GET_CURRENCY_CODE_FAIL";

export const UPDATE_CURRENCY_CODE = "UPDATE_CURRENCY_CODE";
export const UPDATE_CURRENCY_CODE_SUCCESS = "UPDATE_CURRENCY_CODE_SUCCESS";
export const UPDATE_CURRENCY_CODE_FAIL = "UPDATE_CURRENCY_CODE_FAIL";

export const ADD_CURRENCY_CODE = "ADD_CURRENCY_CODE";
export const ADD_CURRENCY_CODE_SUCCESS = "ADD_CURRENCY_CODE_SUCCESS";
export const ADD_CURRENCY_CODE_FAIL = "ADD_CURRENCY_CODE_FAIL";

export const DELETE_CURRENCY_CODE = "DELETE_CURRENCY_CODE";
export const DELETE_CURRENCY_CODE_SUCCESS = "DELETE_CURRENCY_CODE_SUCCESS";
export const DELETE_CURRENCY_CODE_FAIL = "DELETE_CURRENCY_CODE_FAIL";
