export const GET_PAYMENT_TERM = "GET_PAYMENT_TERM";
export const GET_PAYMENT_TERM_SUCCESS = "GET_PAYMENT_TERM_SUCCESS";
export const GET_PAYMENT_TERM_FAIL = "GET_PAYMENT_TERM_FAIL";

export const UPDATE_PAYMENT_TERM = "UPDATE_PAYMENT_TERM";
export const UPDATE_PAYMENT_TERM_SUCCESS = "UPDATE_PAYMENT_TERM_SUCCESS";
export const UPDATE_PAYMENT_TERM_FAIL = "UPDATE_PAYMENT_TERM_FAIL";

export const ADD_PAYMENT_TERM = "ADD_PAYMENT_TERM";
export const ADD_PAYMENT_TERM_SUCCESS = "ADD_PAYMENT_TERM_SUCCESS";
export const ADD_PAYMENT_TERM_FAIL = "ADD_PAYMENT_TERM_FAIL";

export const DELETE_PAYMENT_TERM = "DELETE_PAYMENT_TERM";
export const DELETE_PAYMENT_TERM_SUCCESS = "DELETE_PAYMENT_TERM_SUCCESS";
export const DELETE_PAYMENT_TERM_FAIL = "DELETE_PAYMENT_TERM_FAIL";
