export const GET_PURCHASE_AGREEMENT = "GET_PURCHASE_AGREEMENT";
export const GET_PURCHASE_AGREEMENT_SUCCESS = "GET_PURCHASE_AGREEMENT_SUCCESS";
export const GET_PURCHASE_AGREEMENT_FAIL = "GET_PURCHASE_AGREEMENT_FAIL";

export const GET_SPECIFIC_PURCHASE_AGREEMENT = "GET_SPECIFIC_PURCHASE_AGREEMENT";
export const GET_SPECIFIC_PURCHASE_AGREEMENT_SUCCESS = "GET_SPECIFIC_PURCHASE_AGREEMENT_SUCCESS";
export const GET_SPECIFIC_PURCHASE_AGREEMENT_FAIL = "GET_SPECIFIC_PURCHASE_AGREEMENT_FAIL";

export const POST_PURCHASE_AGREEMENT = "POST_PURCHASE_AGREEMENT";
export const POST_PURCHASE_AGREEMENT_SUCCESS = "POST_PURCHASE_AGREEMENT_SUCCESS";
export const POST_PURCHASE_AGREEMENT_FAIL = "POST_PURCHASE_AGREEMENT_FAIL";

export const UPDATE_PURCHASE_AGREEMENT = "UPDATE_PURCHASE_AGREEMENT";
export const UPDATE_PURCHASE_AGREEMENT_SUCCESS = "UPDATE_PURCHASE_AGREEMENT_SUCCESS";
export const UPDATE_PURCHASE_AGREEMENT_FAIL = "UPDATE_PURCHASE_AGREEMENT_FAIL";

export const RESET_PURCHASE_AGREEMENT_STATUS = "RESET_PURCHASE_AGREEMENT_STATUS";

export const DELETE_PURCHASE_AGREEMENT = "DELETE_PURCHASE_AGREEMENT";
export const DELETE_PURCHASE_AGREEMENT_SUCCESS = "DELETE_PURCHASE_AGREEMENT_SUCCESS";
export const DELETE_PURCHASE_AGREEMENT_FAIL = "DELETE_PURCHASE_AGREEMENT_FAIL";
